### ISSUE TITLE
support evil key sequences

### ISSUE THREAD

**Issue by user471** [justbur/emacs-which-key#99]
which-key could show keys after `y` and other keys.

https://github.com/syl20bnr/spacemacs/issues/4800#issuecomment-174968788
>The issue with y is that as far as Emacs is concerned it is a complete command. After y, evil "manually" reads the subsequent key strokes outside of the usual Emacs mechanism for doing this. That's why which-key is not displaying. 

Then why does `yi` work?

**Comment by justbur** [comment]
@user471 I took a shot at this. It's probably not 100% accurate, but it will show you the usual things you can do after "y", "d", "c" etc. 

The variable you need to set to enable the feature is `which-key-show-operator-state-maps`.

The reason `yi` "works" is after you hit `i` you are in the middle of an incomplete key sequence again. 

Which-key works by detecting when you are in the middle of an incomplete key sequence and showing all of the available bindings that follow. 

The way evil works. `y` is a complete command, so you are not in the middle of a key sequence after `y`. Evil reads the following keys using internal functions which don't register the same way from which-key's perspective. With the new option I just added, I can detect when this is occurring by detecting a change in evil's state, which is a hack, and which is why this is labeled experimental for now.

**Comment by user471** [comment]
Thanks. There is a bug. When you press `ESC` after `y`, it delete current line.

**Comment by justbur** [comment]
Thanks should be fixed in 9c93581566ac66f00af870aeb11aef53dee4d39c

**Comment by user471** [comment]
>The way evil works y is a complete command, so you are not in the middle of a key sequence after y.

What about commands like `@` or `"[a-z]`? Are they also complete command?

> I can detect when this is occurring by detecting a change in evil's state, which is a hack, and which is why this is labeled experimental for now. 

Maybe you could open an issue at evil for some sort of api for this?

**Comment by justbur** [comment]
I can look into these when I get a chance. I can say that they are not
normal prefix commands because if they were which-key would pop up.

**Comment by justbur** [comment]
Ok I looked into it `@`, `'` and `"` don't read from keymaps, so which-key is not really appropriate for them, which is designed to display keymaps. 

It's a good idea, but it would be more appropriate to write new commands that display a list of available marks in the buffer after `'` for example.

**Comment by user471** [comment]
small problems
1. Window shows `(1 of 2)` but paging doesn't work
2. after ``` y` ``` `which-key` still show keys

**Comment by justbur** [comment]
When does 1 happen?

I'll try to fix 2, but it's not going to be easy

**Comment by user471** [comment]
1) `y`
![keys](https://cloud.githubusercontent.com/assets/5988253/12755104/27bf05ce-c9df-11e5-8dbc-ea38c0f70e76.png)
2) It could be confusing for new users, but on the other hand they don't use `which-key-show-operator-state-maps` so maybe It isn't worth it

**Comment by justbur** [comment]
After https://github.com/justbur/emacs-which-key/commit/e1f2e6be99633906865ec3aba0454a0d50d6dba3 I think I've gotten most of the problems with this fixed. I introduced some special handling for the backquote, too.

If you notice other problems, feel free to reopen this issue
